---
# tasks file for git - Debian

- name: Installing {{ git_app }} on Debian systems
  apt:
    name: "{{ git_app }}"
    state: "{{ git_desired_state }}"
    force_apt_get: yes
    update_cache: yes
